// @vitest-environment node

import fs from 'fs'
import os from 'os'
import path from 'path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type Database from 'better-sqlite3'
import { createPlanningHistoryStore } from '../electron/planningHistory'

vi.mock('../electron/logger', () => ({
  logger: {
    debug: vi.fn(),
    info: vi.fn(),
    log: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  },
}))

type DatabaseModule = {
  initialize: () => void
  setCustomDbPath: (filepath: string) => void
  getDb: () => Database.Database
  exportBackupData: () => Record<string, unknown>
  restoreBackupData: (data: Record<string, unknown>, manifestSchemaVersion?: number) => void
}

const databases: Database.Database[] = []
const tempRoots: string[] = []

function makeTempRoot(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'minddiary-planning-restore-'))
  tempRoots.push(root)
  return root
}

async function loadDatabase(): Promise<DatabaseModule> {
  vi.resetModules()
  vi.doMock('electron', () => ({
    app: {
      getPath: vi.fn(() => makeTempRoot()),
      isPackaged: false,
    },
    safeStorage: {
      isEncryptionAvailable: vi.fn(() => false),
      encryptString: vi.fn((value: string) => Buffer.from(value)),
      decryptString: vi.fn((value: Buffer) => value.toString('utf8')),
    },
  }))
  vi.doMock('../electron/mistakeImageStorage', () => ({
    deleteManagedMistakeImage: vi.fn(async () => undefined),
    getMistakeImageReferenceKey: vi.fn(() => null),
  }))
  const imported = await import('../electron/database') as unknown as DatabaseModule | { default: DatabaseModule }
  return 'default' in imported ? imported.default : imported
}

const contextSummaryJson = JSON.stringify([
  { category: 'available_minutes', preparation: 'prepared', disposition: 'included', reasonCode: 'included_required' },
  { category: 'today_tasks', preparation: 'prepared', disposition: 'included', reasonCode: 'included_required' },
  { category: 'due_mistakes', preparation: 'prepared', disposition: 'included', reasonCode: 'included_required' },
  { category: 'subjects', preparation: 'prepared', disposition: 'included', reasonCode: 'included_required' },
  { category: 'today_entry', preparation: 'prepared', disposition: 'included', reasonCode: 'included_required' },
  { category: 'chapters', preparation: 'prepared', disposition: 'included', reasonCode: 'included_required' },
  { category: 'focus_history', preparation: 'prepared', disposition: 'included', reasonCode: 'included_required' },
])

const planningRun = {
  id: '123e4567-e89b-42d3-a456-426614174000',
  contract_version: 'planning-history.v1',
  entry_point: 'today_action',
  planning_date: '2026-08-13',
  target_date: '2026-08-13',
  generation_result_kind: 'candidate_set',
  context_summary_json: contextSummaryJson,
  created_at: '2026-08-13T01:02:03.004Z',
  updated_at: '2026-08-13T01:03:03.004Z',
  closed_at: '2026-08-13T01:03:03.004Z',
  close_reason: 'dialog_closed',
}

const planningCandidate = {
  id: 1,
  planning_run_id: planningRun.id,
  ordinal: 2,
  admission_origin: 'provider_validated',
  title: 'Review chapter three',
  description: 'Use the retained summary',
  type: 'focus',
  estimate_minutes: 25,
  priority: 'high',
  subject_id: 900,
  related_mistake_id: null,
  related_entry_id: 901,
  edit_before_json: JSON.stringify({ title: 'Review chapter two', subject_id: null }),
  user_disposition: 'confirmed',
  operation_id: '223e4567-e89b-42d3-a456-426614174000',
  outcome_kind: 'created',
  outcome_observed_at: '2026-08-13T01:03:03.004Z',
  admitted_at: '2026-08-13T01:02:03.004Z',
  updated_at: '2026-08-13T01:03:03.004Z',
}

afterEach(() => {
  vi.restoreAllMocks()
  vi.doUnmock('electron')
  vi.doUnmock('../electron/mistakeImageStorage')
  for (const database of databases.splice(0)) {
    try {
      database.close()
    } catch {
      // already closed
    }
  }
  for (const root of tempRoots.splice(0)) {
    fs.rmSync(root, { recursive: true, force: true })
  }
})

describe('planning history backup and restore', () => {
  it('roundtrips context and edit JSON generated by the live planning-history store', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare("INSERT INTO subjects (id, name) VALUES (1, 'Math')").run()
    const now = new Date()
    const store = createPlanningHistoryStore({ database, now: () => now })
    const runId = '323e4567-e89b-42d3-a456-426614174000'
    const contextSummary = JSON.parse(contextSummaryJson)

    store.create({
      id: runId,
      entryPoint: 'today_action',
      planningDate: '2026-08-13',
      targetDate: '2026-08-13',
      generationResultKind: 'candidate_set',
      contextSummary,
      candidates: [{
        ordinal: 0,
        admissionOrigin: 'provider_validated',
        title: 'Review chapter two',
        description: 'Use the retained summary',
        type: 'focus',
        estimateMinutes: 25,
        priority: 'high',
        subjectId: 1,
        relatedMistakeId: null,
        relatedEntryId: null,
        userDisposition: 'selected_unconfirmed',
      }],
    })
    store.transition({
      kind: 'commit_candidate',
      runId,
      ordinal: 0,
      candidate: {
        title: 'Review chapter three',
        description: 'Use the retained summary',
        type: 'focus',
        estimateMinutes: 30,
        priority: 'medium',
        subjectId: 1,
        relatedMistakeId: null,
        relatedEntryId: null,
      },
    })

    const backup = module.exportBackupData()
    expect((backup.planning_runs as Array<Record<string, unknown>>)[0]?.context_summary_json).toBe(contextSummaryJson)
    expect((backup.planning_run_candidates as Array<Record<string, unknown>>)[0]?.edit_before_json).toBe(
      JSON.stringify({ title: 'Review chapter two', estimate_minutes: 25, priority: 'high' }),
    )

    module.restoreBackupData(backup, 7)

    expect(store.get(runId)).toEqual(expect.objectContaining({
      id: runId,
      contextSummary,
      candidates: [expect.objectContaining({
        title: 'Review chapter three',
        estimateMinutes: 30,
        priority: 'medium',
        editBefore: {
          title: 'Review chapter two',
          estimateMinutes: 25,
          priority: 'high',
        },
      })],
    }))
  })

  it('roundtrips populated schema 7 planning history through the real SQLite boundary', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare(`
      INSERT INTO planning_runs (
        id, contract_version, entry_point, planning_date, target_date,
        generation_result_kind, context_summary_json, created_at, updated_at,
        closed_at, close_reason
      ) VALUES (
        @id, @contract_version, @entry_point, @planning_date, @target_date,
        @generation_result_kind, @context_summary_json, @created_at, @updated_at,
        @closed_at, @close_reason
      )
    `).run(planningRun)
    database.prepare(`
      INSERT INTO planning_run_candidates (
        id, planning_run_id, ordinal, admission_origin, title, description, type,
        estimate_minutes, priority, subject_id, related_mistake_id, related_entry_id,
        edit_before_json, user_disposition, operation_id, outcome_kind,
        outcome_observed_at, admitted_at, updated_at
      ) VALUES (
        @id, @planning_run_id, @ordinal, @admission_origin, @title, @description, @type,
        @estimate_minutes, @priority, @subject_id, @related_mistake_id, @related_entry_id,
        @edit_before_json, @user_disposition, @operation_id, @outcome_kind,
        @outcome_observed_at, @admitted_at, @updated_at
      )
    `).run(planningCandidate)

    const backup = module.exportBackupData()
    expect(backup.planning_runs).toEqual([planningRun])
    expect(backup.planning_run_candidates).toEqual([planningCandidate])

    module.restoreBackupData(backup, 7)

    expect(database.prepare('SELECT * FROM planning_runs').all()).toEqual([planningRun])
    expect(database.prepare('SELECT * FROM planning_run_candidates').all()).toEqual([planningCandidate])
    expect(database.prepare('PRAGMA foreign_key_check').all()).toEqual([])
    expect(database.prepare('PRAGMA integrity_check').get()).toEqual({ integrity_check: 'ok' })
  })

  it('repairs source AUTOINCREMENT high-water marks from final and edit-before logical references', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare("INSERT INTO subjects (id, name) VALUES (810, 'old subject')").run()
    database.prepare("INSERT INTO entries (id, date, content) VALUES (820, '2026-08-12', 'old entry')").run()
    database.prepare("INSERT INTO mistakes (id, question, answer) VALUES (830, 'old question', 'old answer')").run()
    database.prepare('DELETE FROM subjects').run()
    database.prepare('DELETE FROM entries').run()
    database.prepare('DELETE FROM mistakes').run()
    const danglingCandidate = {
      ...planningCandidate,
      type: 'review',
      subject_id: 1410,
      related_mistake_id: 1430,
      related_entry_id: 1420,
      edit_before_json: JSON.stringify({
        subject_id: 1510,
        related_mistake_id: 1530,
        related_entry_id: 1520,
      }),
      user_disposition: 'unselected',
      operation_id: null,
      outcome_kind: null,
      outcome_observed_at: null,
    }

    module.restoreBackupData({
      planning_runs: [planningRun],
      planning_run_candidates: [danglingCandidate],
    }, 7)

    expect(database.prepare(`
      SELECT subject_id, related_mistake_id, related_entry_id, edit_before_json
      FROM planning_run_candidates
    `).get()).toEqual({
      subject_id: 1410,
      related_mistake_id: 1430,
      related_entry_id: 1420,
      edit_before_json: danglingCandidate.edit_before_json,
    })
    const subjectId = Number(database.prepare("INSERT INTO subjects (name) VALUES ('new subject')").run().lastInsertRowid)
    const entryId = Number(database.prepare("INSERT INTO entries (date, content) VALUES ('2026-08-14', 'new entry')").run().lastInsertRowid)
    const mistakeId = Number(database.prepare("INSERT INTO mistakes (question, answer) VALUES ('new question', 'new answer')").run().lastInsertRowid)

    expect(subjectId).toBeGreaterThan(1510)
    expect(entryId).toBeGreaterThan(1520)
    expect(mistakeId).toBeGreaterThan(1530)
  })

  it('preserves the planning candidate AUTOINCREMENT high-water across restore', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare(`
      INSERT INTO planning_runs (
        id, contract_version, entry_point, planning_date, target_date,
        generation_result_kind, context_summary_json, created_at, updated_at
      ) VALUES (
        @id, @contract_version, @entry_point, @planning_date, @target_date,
        @generation_result_kind, @context_summary_json, @created_at, @updated_at
      )
    `).run(planningRun)
    database.prepare(`
      INSERT INTO planning_run_candidates (
        id, planning_run_id, ordinal, admission_origin, title, description, type,
        estimate_minutes, priority, subject_id, related_mistake_id, related_entry_id,
        edit_before_json, user_disposition, operation_id, outcome_kind,
        outcome_observed_at, admitted_at, updated_at
      ) VALUES (
        900, @planning_run_id, @ordinal, @admission_origin, @title, @description, @type,
        @estimate_minutes, @priority, @subject_id, @related_mistake_id, @related_entry_id,
        @edit_before_json, @user_disposition, @operation_id, @outcome_kind,
        @outcome_observed_at, @admitted_at, @updated_at
      )
    `).run(planningCandidate)

    module.restoreBackupData({ planning_runs: [], planning_run_candidates: [] }, 7)
    database.prepare(`
      INSERT INTO planning_runs (
        id, contract_version, entry_point, planning_date, target_date,
        generation_result_kind, context_summary_json, created_at, updated_at
      ) VALUES (
        @id, @contract_version, @entry_point, @planning_date, @target_date,
        @generation_result_kind, @context_summary_json, @created_at, @updated_at
      )
    `).run(planningRun)
    const candidateId = Number(database.prepare(`
      INSERT INTO planning_run_candidates (
        planning_run_id, ordinal, admission_origin, title, description, type,
        estimate_minutes, priority, subject_id, related_mistake_id, related_entry_id,
        edit_before_json, user_disposition, operation_id, outcome_kind,
        outcome_observed_at, admitted_at, updated_at
      ) VALUES (
        @planning_run_id, @ordinal, @admission_origin, @title, @description, @type,
        @estimate_minutes, @priority, @subject_id, @related_mistake_id, @related_entry_id,
        @edit_before_json, @user_disposition, @operation_id, @outcome_kind,
        @outcome_observed_at, @admitted_at, @updated_at
      )
    `).run(planningCandidate).lastInsertRowid)

    expect(candidateId).toBeGreaterThan(900)
  })

  it('applies the 30-day and maximum-100 run retention policy inside restore', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    const now = Date.now()
    const recentRuns = Array.from({ length: 101 }, (_, index) => {
      const timestamp = new Date(now - index * 60_000).toISOString()
      return {
        ...planningRun,
        id: `00000000-0000-4000-8000-${String(index + 1).padStart(12, '0')}`,
        created_at: timestamp,
        updated_at: timestamp,
        closed_at: null,
        close_reason: null,
      }
    })
    const oldTimestamp = new Date(now - 31 * 24 * 60 * 60 * 1000).toISOString()
    const oldRun = {
      ...planningRun,
      id: 'ffffffff-ffff-4fff-bfff-ffffffffffff',
      created_at: oldTimestamp,
      updated_at: oldTimestamp,
      closed_at: null,
      close_reason: null,
    }
    const oldCandidate = {
      ...planningCandidate,
      planning_run_id: oldRun.id,
      user_disposition: 'unselected',
      operation_id: null,
      outcome_kind: null,
      outcome_observed_at: null,
      admitted_at: oldTimestamp,
      updated_at: oldTimestamp,
    }

    module.restoreBackupData({
      planning_runs: [...recentRuns, oldRun],
      planning_run_candidates: [oldCandidate],
    }, 7)

    const rows = database.prepare('SELECT id FROM planning_runs ORDER BY created_at DESC, id DESC').all() as Array<{ id: string }>
    expect(rows).toHaveLength(100)
    expect(rows[0]?.id).toBe(recentRuns[0]?.id)
    expect(rows.some(row => row.id === recentRuns[100]?.id)).toBe(false)
    expect(rows.some(row => row.id === oldRun.id)).toBe(false)
    expect(database.prepare('SELECT COUNT(*) AS count FROM planning_run_candidates').get()).toEqual({ count: 0 })
  })

  it('normalizes a schema 6 restore without planning sections to empty history', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare(`
      INSERT INTO planning_runs (
        id, contract_version, entry_point, planning_date, target_date,
        generation_result_kind, context_summary_json, created_at, updated_at,
        closed_at, close_reason
      ) VALUES (
        @id, @contract_version, @entry_point, @planning_date, @target_date,
        @generation_result_kind, @context_summary_json, @created_at, @updated_at,
        @closed_at, @close_reason
      )
    `).run(planningRun)

    module.restoreBackupData({ settings: [] }, 6)

    expect(database.prepare('SELECT COUNT(*) AS count FROM planning_runs').get()).toEqual({ count: 0 })
    expect(module.exportBackupData().planning_runs).toEqual([])
    expect(module.exportBackupData().planning_run_candidates).toEqual([])
  })

  it('rolls back all imported tables when a real SQLite foreign-key failure occurs', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare(`
      INSERT INTO planning_runs (
        id, contract_version, entry_point, planning_date, target_date,
        generation_result_kind, context_summary_json, created_at, updated_at,
        closed_at, close_reason
      ) VALUES (
        @id, @contract_version, @entry_point, @planning_date, @target_date,
        @generation_result_kind, @context_summary_json, @created_at, @updated_at,
        @closed_at, @close_reason
      )
    `).run(planningRun)
    database.prepare(`
      INSERT INTO study_tasks (id, title, planned_date, status, source)
      VALUES (1, 'preserved task', '2026-08-13', 'todo', 'ai')
    `).run()

    expect(() => module.restoreBackupData({
      planning_runs: [],
      planning_run_candidates: [],
      study_task_action_receipts: [{
        operation_id: '323e4567-e89b-42d3-a456-426614174000',
        operation_kind: 'today_action',
        action_contract_version: 'confirmed-study-task-action.v1',
        request_digest: 'a'.repeat(64),
        expected_current_date: '2026-08-13',
        planned_date: '2026-08-13',
        task_id: 999,
        created_at: '2026-08-13T01:00:00.000Z',
      }],
    }, 7)).toThrow(/foreign key/i)

    expect(database.prepare('SELECT id FROM planning_runs').all()).toEqual([{ id: planningRun.id }])
    expect(database.prepare('SELECT id, title FROM study_tasks').all()).toEqual([{ id: 1, title: 'preserved task' }])
    expect(database.prepare('PRAGMA foreign_key_check').all()).toEqual([])
    expect(database.prepare('PRAGMA integrity_check').get()).toEqual({ integrity_check: 'ok' })
  })

  it('rolls back an otherwise valid import when the real SQLite integrity check is not ok', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare(`
      INSERT INTO planning_runs (
        id, contract_version, entry_point, planning_date, target_date,
        generation_result_kind, context_summary_json, created_at, updated_at,
        closed_at, close_reason
      ) VALUES (
        @id, @contract_version, @entry_point, @planning_date, @target_date,
        @generation_result_kind, @context_summary_json, @created_at, @updated_at,
        @closed_at, @close_reason
      )
    `).run(planningRun)
    database.exec(`
      CREATE TABLE integrity_sentinel (value INTEGER CHECK (value = 1));
      PRAGMA ignore_check_constraints = ON;
      INSERT INTO integrity_sentinel (value) VALUES (2);
      PRAGMA ignore_check_constraints = OFF;
    `)
    expect(database.prepare('PRAGMA integrity_check').all()).not.toEqual([{ integrity_check: 'ok' }])

    expect(() => module.restoreBackupData({
      planning_runs: [],
      planning_run_candidates: [],
    }, 7)).toThrow(/integrity_check/i)

    expect(database.prepare('SELECT id FROM planning_runs').all()).toEqual([{ id: planningRun.id }])
  })

  it('preflights corrupt schema 7 planning rows before deleting the existing database contents', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare(`
      INSERT INTO planning_runs (
        id, contract_version, entry_point, planning_date, target_date,
        generation_result_kind, context_summary_json, created_at, updated_at,
        closed_at, close_reason
      ) VALUES (
        @id, @contract_version, @entry_point, @planning_date, @target_date,
        @generation_result_kind, @context_summary_json, @created_at, @updated_at,
        @closed_at, @close_reason
      )
    `).run(planningRun)

    expect(() => module.restoreBackupData({
      planning_runs: [{ ...planningRun, context_summary_json: '[]' }],
      planning_run_candidates: [],
      study_tasks: [{ id: 2, title: 'must not import' }],
    }, 7)).toThrow(/context_summary_json/i)

    expect(database.prepare('SELECT id FROM planning_runs').all()).toEqual([{ id: planningRun.id }])
    expect(database.prepare('SELECT COUNT(*) AS count FROM study_tasks').get()).toEqual({ count: 0 })
  })

  it('preflights impossible edit_before_json reconstructed snapshot before mutating the database', async () => {
    const module = await loadDatabase()
    module.setCustomDbPath(path.join(makeTempRoot(), 'minddiary.db'))
    module.initialize()
    const database = module.getDb()
    databases.push(database)
    database.prepare(`
      INSERT INTO planning_runs (
        id, contract_version, entry_point, planning_date, target_date,
        generation_result_kind, context_summary_json, created_at, updated_at,
        closed_at, close_reason
      ) VALUES (
        @id, @contract_version, @entry_point, @planning_date, @target_date,
        @generation_result_kind, @context_summary_json, @created_at, @updated_at,
        @closed_at, @close_reason
      )
    `).run(planningRun)

    expect(() => module.restoreBackupData({
      planning_runs: [planningRun],
      planning_run_candidates: [{
        ...planningCandidate,
        type: 'focus',
        related_mistake_id: null,
        edit_before_json: JSON.stringify({ related_mistake_id: 12 }),
      }],
      study_tasks: [{ id: 2, title: 'must not import' }],
    }, 7)).toThrow(/reconstructed.*before.*inconsistent/i)

    expect(database.prepare('SELECT id FROM planning_runs').all()).toEqual([{ id: planningRun.id }])
    expect(database.prepare('SELECT COUNT(*) AS count FROM study_tasks').get()).toEqual({ count: 0 })
  })
})
