// @vitest-environment node

import { describe, expect, it } from 'vitest'
import {
  getAutoUpdateNotConfiguredStatus,
  hasPublishConfiguration,
  isAutoUpdateConfigured,
} from '../electron/updaterConfig'

describe('updater configuration guard', () => {
  it('reports a clear downgrade status when no update source is configured', () => {
    expect(isAutoUpdateConfigured({
      isPackaged: true,
      appUpdateConfigPath: 'C:\\missing\\app-update.yml',
      fsExists: () => false,
      packageMetadata: { build: {} },
    })).toBe(false)

    expect(getAutoUpdateNotConfiguredStatus()).toEqual({
      status: 'auto-update-not-configured',
      message: '当前版本未配置自动更新源',
    })
  })

  it('accepts an app-update.yml generated by electron-builder', () => {
    expect(isAutoUpdateConfigured({
      isPackaged: true,
      appUpdateConfigPath: 'C:\\app\\resources\\app-update.yml',
      fsExists: () => true,
      packageMetadata: { build: {} },
    })).toBe(true)
  })

  it('accepts package publish configuration as an explicit fallback', () => {
    expect(isAutoUpdateConfigured({
      isPackaged: true,
      appUpdateConfigPath: 'C:\\missing\\app-update.yml',
      fsExists: () => false,
      packageMetadata: {
        build: {
          publish: [{ provider: 'github', owner: 'gakialter', repo: 'Minddiary' }],
        },
      },
    })).toBe(true)
  })

  it('recognizes a real GitHub publish configuration and rejects placeholders', () => {
    expect(hasPublishConfiguration({
      build: {
        publish: [{ provider: 'github', owner: 'gakialter', repo: 'Minddiary' }],
      },
    })).toBe(true)

    expect(hasPublishConfiguration({
      build: {
        publish: [{ provider: 'github', owner: 'YourOrg', repo: 'YourRepo' }],
      },
    })).toBe(false)
  })
})
