import React, { forwardRef } from 'react';
import { marked } from 'marked';
import DOMPurify from 'dompurify';

const ShareCard = forwardRef(({ diary, pomodoros = [] }, ref) => {
  // 计算今天总专注时长 (分钟)
  const totalFocusMinutes = pomodoros.reduce((total, p) => total + (p.duration / 60), 0);

  // 安全渲染 Markdown
  const renderMarkdown = (content) => {
    return { __html: DOMPurify.sanitize(marked(content || '今天没有记录任何感悟。')) };
  };

  return (
    <div style={{ position: 'absolute', left: '-9999px', top: 0 }}>
      {/* 必须给 ref 绑定到真正用来截图的 wrapper 上，同时给定一个固定的宽度，比如 800px，保证生成出的图片比例完美 */}
      <div ref={ref} className="share-card-wrapper" style={{ width: '800px', padding: '40px', background: 'var(--bg-primary)' }}>

        <div className="share-card-header">
          <h2>{diary?.title || '未命名日记'}</h2>
          <div className="share-card-date">{diary?.date}</div>
        </div>

        <div className="share-card-body markdown-body"
             dangerouslySetInnerHTML={renderMarkdown(diary?.content)} />

        <div className="share-card-footer">
          <div className="footer-stats">
            🍅 今日专注: <strong>{Math.round(totalFocusMinutes)}</strong> 分钟
          </div>
          <div className="footer-brand">
            — Generated by MindDiary
          </div>
        </div>

      </div>
    </div>
  );
});

ShareCard.displayName = 'ShareCard';

export default ShareCard;
