#!/bin/bash

# Gstack E2E Test Script for MindDiary
# This script uses the Gstack headless browser CLI ($B) to test core flows.

# Ensure we have the CLI available (assuming $B aliases the gstack binary)
if ! command -v $B &> /dev/null
then
    echo "Gstack CLI ($B) not found. Please ensure it is installed and aliased as \$B."
    # Fallback to gstack if available
    export B="gstack"
fi

APP_URL=${1:-"http://localhost:5173"}

echo "======================================"
echo "🚀 Starting E2E tests for MindDiary..."
echo "======================================"

# Start Gstack and open the app
echo "[1/2] Testing Core Flow: Write Diary -> Save"
$B nav "$APP_URL"
sleep 2 # Wait for initial load

# Navigate to Diary page (assuming Dashboard or Editor is the default view, or we click sidebar)
# Wait for editor to appear by ensuring we are on the daily page
$B verify "document.querySelector('.editor-textarea')"

# Type a diary entry
echo "Typing entry..."
$B click ".editor-textarea"
$B type "E2E Test Entry: Automatically generated by Gstack."

# Verify that auto-save happens or manually verify the content is present
$B verify "document.querySelector('.editor-textarea').value.includes('E2E Test Entry')"
echo "✅ Diary entry verified."

# ---------------------------------------------------------
echo "[2/2] Testing Core Flow: Pomodoro completeness"
# Navigate to Pomodoro (assuming sidebar link or widget exists)
echo "Opening Pomodoro timer..."
$B click "div.pomodoro-mini, [aria-label='番茄钟']"
sleep 1
# Verify we are on the Pomodoro page
$B verify "document.body.innerText.includes('准备就绪')"

# Click "开始专注"
echo "Starting Pomodoro session..."
$B click "button:has-text('开始专注')"
sleep 1

# Since we don't want to actually wait 25 minutes in a test:
# We can execute a script to fast-forward the timer or mock Date.now if possible.
# Alternatively, we just verify the state transition into '正在进行中...'
$B verify "document.body.innerText.includes('正在进行中')"
echo "✅ Pomodoro started successfully."

# Stop or Reset Timer to clean up state
echo "Resetting timer..."
$B click "[aria-label='重置番茄钟']"
sleep 1
$B verify "document.body.innerText.includes('准备就绪')"
echo "✅ Pomodoro reset successfully."

echo "======================================"
echo "🎉 All Gstack E2E flows passed."
echo "======================================"
